### class classname:
    # some function and variables
    # function - used to perform the specific activity
    # variables - data(memory)

In [4]:
def test():
    print("test() for function")
    return
test()

test() for function


In [3]:
class demo:
    def test(self):
        print("test() for class and method")
        return

obj = demo()
obj.test()

test() for class and method


In [19]:
class demo1():
    def fact(self,n):
        fact = 1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1 = demo1()
print(p1.fact(5))

120


In [22]:
class demo2():
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
        return p1+p2
    
c1=demo2(10,20)
print(c1.add(100,200))

300


In [24]:
import re
sum = 0
pattern='back'
if re.match(pattern,'backup.txt'):
    sum+=1
if re.match(pattern,'text.back'):
    sum+=2
if re.match(pattern,'backup.txt'):
    sum+=4
if re.match(pattern,'text.back'):
    sum+=8
print(sum)

5


In [3]:
import re
sentence='we are humans'
matched=re.match(r'(.*?)(.*)',sentence)
print(matched.group(2))

we are humans


In [2]:
class person(object):
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
    
class employee(person):
    def isemployee(self):
        return True
emp=person("anil")
print(emp.getname(),emp.isemployee())

emp1=employee("akhil")
print(emp1.getname(),emp1.isemployee())


anil False
akhil True


In [3]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [5]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [8]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [11]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [12]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(6,1)

[[1 2 3]
 [4 5 6]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [13]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [14]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [15]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [17]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [19]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [21]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [23]:
a1=np.array([(1,2,3),(4,5,6)])
print("First Row:",a1[0])

First Row: [1 2 3]


In [24]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing coloumn:",a1[:,1])

Slicing coloumn: [2 5]


In [25]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing last coloumn:",a1[:,2])

Slicing last coloumn: [3 6]


In [26]:
a1=np.array([(1,2,3),(4,5,6)])
print("row and  coloumn:",a1[1:,1])

row and  coloumn: [5]


In [29]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value:",np.min(a1))
print("max value:",np.max(a1))
print("median value:",np.median(a1))
print("mean value:",np.mean(a1))

[6.43647351 5.65257626 4.08955653 3.72988131 4.23173813 4.46812659
 5.05548675 3.5425298  5.48725977 4.70793384]
min value: 3.5425298041005013
max value: 6.436473510627736
median value: 4.588030216649127
mean value: 4.740156249614139


In [30]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [32]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [33]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,5)])
np.dot(b1,b2)

array([[ 6, 28],
       [15, 63]])

# pandas basics
### pandas data frames
###   data analysis with python
### python is one of the popular programming language for data analysis 

In [1]:
import pandas as pd
dict ={"Name":["anil","akhil","dinesh","harsha","ajay","kranth"],
      "Emailid":["anil01@gmail.com","akhil02gmail.com","dinesh03@gmail.com","harsha042gmail.com","ajay05@gmail.com","kranth06@gmail.com"],
      "MobileNumber":["111","222","333","444","555","666"]}
b=pd.DataFrame(dict)
print(b)

     Name             Emailid MobileNumber
0    anil    anil01@gmail.com          111
1   akhil    akhil02gmail.com          222
2  dinesh  dinesh03@gmail.com          333
3  harsha  harsha042gmail.com          444
4    ajay    ajay05@gmail.com          555
5  kranth  kranth06@gmail.com          666


In [2]:
b.index=["01","02","03","04","05","06"]
print(b)

      Name             Emailid MobileNumber
01    anil    anil01@gmail.com          111
02   akhil    akhil02gmail.com          222
03  dinesh  dinesh03@gmail.com          333
04  harsha  harsha042gmail.com          444
05    ajay    ajay05@gmail.com          555
06  kranth  kranth06@gmail.com          666


In [ ]:
import pandas as pd
products=pd.read_csv("filename.csv")
print(products

# TASK

In [7]:
def frequency(a):
    i=0
    while(i<=9):
        count=0
        for j in range(len(a)):
            if(ord(a[j])>=48 and ord(a[j])<=56):
                if i==int(a[j]):
                    count=count+1
        print(count,end=" ")
        i=i+1
a="213abc456def111"
frequency(a)
                

0 4 1 1 1 1 1 0 0 0 

In [8]:
def check(s1,s2):
    if(sorted(s1) == sorted(s2)):
        print("the strings are anagrams.")
    else:
        print("the strings arent anagrams.")
s1="listen"
s2="silent"
check(s1,s2)

the strings are anagrams.
